site_name: Biblical Studies by ding0t
site_url: 'https://gh-ding0t.github.io/bible_end_times/'
repo_url: 'https://github.com/ding0t/bible_end_times'
docs_dir: docs/content

theme:
  name: material
  palette:
    scheme: default
    primary: blue
  features:
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.top

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  # enable code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # allow inclusion of files outside docs
  - pymdownx.snippets
  - pymdownx.details
  # use pretty task lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # emojis - search here https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg