site_name: Biblical Studies by ding0t
site_url: ''
repo_url: 'https://github.com/ding0t/bible_end_times'
#docs_dir: docs

# main navigation
nav:
#  - Be prepared: "apologetics/be_prepared.md"
#  - On teaching: "apologetics/on_teaching.md"


# material theme has good documentation and configuration
theme:
  name: material
  palette:
    scheme: default
    primary: blue
  features:
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.expand

# pip install mkdocstrings[python]
# https://realpython.com/python-project-documentation-with-mkdocs/
plugins:
  - tags
  - search

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  # enable code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # allow inclusion of files outside docs
  - pymdownx.snippets
  - pymdownx.details
  # use pretty task lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # emojis - search here https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg