"""Fills in the provenance frontmatter fields -- date_created, date_modified and
ai_provider_models -- on the hand-written pages under docs/content, deriving every value from
git history rather than asking anyone to remember.

  date_created        the date of the file's first commit (--follow, so the taxonomy migration's
                      renames don't reset a 2025 study to its 2026 move date)
  date_modified       the date of its most recent commit
  ai_provider_models  every model that has touched the file, from the Co-Authored-By trailers on
                      the commits that touched it, as provider-qualified slugs

Why a script and not hand-maintenance: the repo already learned this lesson once. Dates typed
into frontmatter go stale the moment someone edits a file and forgets, which is why
generate_recent_updates.py derives "recently updated" from git log instead. These fields exist as
a provenance record, so they are worth having -- but they are worth having *correct*, and git
already knows the answer. validate-content.js check 17 warns when a file's date_modified has
fallen behind its last commit, so drift gets caught even if you forget.

**Run this before committing, not after.** A file with uncommitted changes gets today's date,
because today is when the commit you are about to make will land; a clean file gets its real last
commit date. Running it afterwards instead cannot converge -- stamping the dates is itself a
change to all 93 files, so the commit that records them moves every file's last-commit date one
commit further on, and check 17 then flags every page. Stage the provenance edit together with the
content edit and the two agree by construction.

Scope is deliberately the ~93 hand-written pages. The 432 commentary cross-reference pages are
generated by commentary_index.py and are identified by their auto-section marker; stamping a
provenance record on a file a script wrote on demand would be recording the script run, not
authorship, and their date_modified would churn on every regeneration.

Merging, not overwriting: ai_provider_models is unioned with whatever is already in the file, so
a model recorded by hand (one that worked on a page before it was ever committed, say) survives a
re-run.

stdlib-only, same as the other utils/ scripts, so it needs no venv. Requires full git history.

Usage: python3 utils/refresh_frontmatter_provenance.py [--check]

  --check  report what would change and exit 1 if anything would, without writing. For CI or a
           pre-commit hook.
"""
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = REPO_ROOT / "docs" / "content"

# A page is generated, not written, if it carries commentary_index.py's marker.
GENERATED_MARKER = "<!-- commentary-index:auto-start -->"

PROVENANCE_FIELDS = ("date_created", "date_modified", "ai_provider_models")

# "Claude Opus 4.5 <noreply@anthropic.com>" -> "anthropic/claude-opus-4.5". Every trailer in this
# repo's history is an Anthropic model; the provider is taken from the trailer's email domain so a
# future non-Anthropic co-author slugs correctly rather than being silently mislabelled.
TRAILER = re.compile(r"^(?P<name>.+?)\s*<[^@]*@(?P<domain>[^.>]+)")


def model_slug(trailer_value: str) -> str | None:
    match = TRAILER.match(trailer_value.strip())
    if not match:
        return None
    name = match.group("name").strip().lower().replace(" ", "-")
    return f"{match.group('domain').lower()}/{name}"


def git_history(path: Path) -> tuple[str | None, str | None, list[str]]:
    """Returns (first commit date, last commit date, model slugs) for one file.

    --follow keeps a file's history across the renames of the 2026-08 taxonomy migration, which
    moved most of docs/content. Without it every moved study would claim to have been created on
    the day it was moved.
    """
    result = subprocess.run(
        [
            "git", "log", "--follow", "--date=short",
            "--format=%ad\x1f%(trailers:key=Co-authored-by,valueonly,separator=\x1e)",
            "--", str(path.relative_to(REPO_ROOT)),
        ],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    lines = [line for line in result.stdout.splitlines() if line.strip()]
    if not lines:
        return None, None, []

    models = set()
    dates = []
    for line in lines:
        commit_date, _, trailers = line.partition("\x1f")
        dates.append(commit_date.strip())
        for trailer in trailers.split("\x1e"):
            if not trailer.strip():
                continue
            slug = model_slug(trailer)
            if slug:
                models.add(slug)
    # git log is newest-first.
    return dates[-1], dates[0], sorted(models)


def dirty_paths() -> set[str]:
    """Content paths with uncommitted changes, staged or not, including untracked files.

    These get today's date rather than their last commit's, because the commit about to be made
    is the one the provenance record should name. See the module docstring on why running after
    the commit instead cannot converge.
    """
    result = subprocess.run(
        ["git", "status", "--porcelain", "--", "docs/content"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    paths = set()
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        entry = line[3:].strip()
        # Renames read as "old -> new"; the new path is the one on disk.
        if " -> " in entry:
            entry = entry.split(" -> ", 1)[1]
        paths.add(entry.strip('"'))
    return paths


def split_frontmatter(text: str) -> tuple[list[str], str] | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    return text[4:end].splitlines(), text[end + 5:]


def existing_models(fm_lines: list[str]) -> list[str]:
    """Reads an existing ai_provider_models block, in either YAML list style."""
    for i, line in enumerate(fm_lines):
        if not line.startswith("ai_provider_models:"):
            continue
        inline = line.split(":", 1)[1].strip()
        if inline.startswith("["):
            return [v.strip().strip("\"'") for v in inline.strip("[]").split(",") if v.strip()]
        models = []
        for follow in fm_lines[i + 1:]:
            if not follow.startswith("  - "):
                break
            models.append(follow[4:].strip().strip("\"'"))
        return models
    return []


def strip_provenance(fm_lines: list[str]) -> list[str]:
    kept = []
    skipping = False
    for line in fm_lines:
        if skipping:
            if line.startswith("  - ") or line.startswith("  -"):
                continue
            skipping = False
        field = line.split(":", 1)[0].strip()
        if field in PROVENANCE_FIELDS:
            skipping = field == "ai_provider_models"
            continue
        kept.append(line)
    return kept


def render(fm_lines: list[str], created: str, modified: str, models: list[str]) -> str:
    lines = list(fm_lines)
    lines.append(f"date_created: {created}")
    lines.append(f"date_modified: {modified}")
    if models:
        lines.append("ai_provider_models:")
        lines.extend(f"  - {m}" for m in models)
    else:
        lines.append("ai_provider_models: []")
    return "\n".join(lines)


def hand_written_pages() -> list[Path]:
    pages = []
    for path in sorted(CONTENT_DIR.rglob("*.md")):
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            continue
        pages.append(path)
    return pages


def main() -> int:
    check_only = "--check" in sys.argv
    today = date.today().isoformat()
    dirty = dirty_paths()
    changed = []
    skipped = []

    for path in hand_written_pages():
        text = path.read_text(encoding="utf-8")
        split = split_frontmatter(text)
        if split is None:
            skipped.append((path, "no frontmatter block"))
            continue
        fm_lines, body = split

        created, modified, models = git_history(path)
        if created is None:
            # Never committed -- record today and keep whatever the author already put there.
            created = modified = today
        elif str(path.relative_to(REPO_ROOT)) in dirty:
            modified = today
        models = sorted(set(models) | set(existing_models(fm_lines)))

        rebuilt = f"---\n{render(strip_provenance(fm_lines), created, modified, models)}\n---\n{body}"
        if rebuilt == text:
            continue
        changed.append(path)
        if not check_only:
            path.write_text(rebuilt, encoding="utf-8")

    for path, reason in skipped:
        print(f"skipped: {path.relative_to(REPO_ROOT)} ({reason})")
    verb = "would update" if check_only else "updated"
    print(f"{verb} {len(changed)} of {len(hand_written_pages())} hand-written page(s).")
    for path in changed:
        print(f"  {verb}: {path.relative_to(REPO_ROOT)}")

    return 1 if (check_only and changed) else 0


if __name__ == "__main__":
    raise SystemExit(main())
